#!/usr/bin/env python3
"""
Hermes Brain — sample/demo data seeder.

Populates Daily/, Memory-Review/, Projects/, and Skills-Notes/Token-Usage.log
with realistic-looking FAKE data, so a freshly cloned/installed vault shows
a populated Dashboard and graph view instead of an empty one on first open.

This is NOT meant to ship pre-populated. Run it yourself when you want to
preview/demo the vault (e.g. alongside try.sh), then delete the generated
files before using the vault for real — or just don't run this on a vault
that already has real Daily/ content, since it writes into the same tree.

Usage:
    python3 Scripts/seed_sample_data.py <vault_root>
    (or with HERMES_VAULT_PATH set, no arg needed)

Every generated file's frontmatter is tagged `sample: true` so it's easy to
find and remove later:
    grep -rl "sample: true" Daily/ Memory-Review/ Projects/ | xargs rm
"""
import json
import os
import sys
from datetime import datetime, timedelta

SAMPLE_SESSIONS = [
    {
        "offset_days": 6,
        "title": "Setting up Docker Compose for a self-hosted stack",
        "tokens": (1450, 620),
        "messages": 18,
        "body": """**User:** I want to run three containers — a reverse proxy, an app, and
Postgres — all behind one Compose file. What's a clean way to structure it?

**Assistant:** Split into a `docker-compose.yml` with a dedicated bridge
network, named volumes for Postgres data, and `depends_on` with healthchecks
so the app waits for the DB to actually be ready, not just started...

**User:** Should I pin image versions or use `latest`?

**Assistant:** Always pin — `latest` silently changes under you on rebuild
and breaks reproducibility. Use a specific tag or digest...
""",
    },
    {
        "offset_days": 4,
        "title": "Debugging a cron job that silently stopped firing",
        "tokens": (980, 410),
        "messages": 12,
        "body": """**User:** My hourly cron job hasn't written a new file in two days but
shows no errors anywhere.

**Assistant:** Silent-stop with no error usually means the process is
exiting 0 before doing real work — check for an early return on an
unexpected condition, or a PATH issue where a dependency it calls
(like a CLI binary) resolved differently than when you tested manually...

**User:** Found it — the script found zero new items and returned early
without logging that it did so.

**Assistant:** That's the classic case — always log the "nothing to do"
path too, not just the "did work" and error paths, so silence is
distinguishable from "working, but idle" in the logs...
""",
    },
    {
        "offset_days": 2,
        "title": "Comparing Obsidian Dataview vs a custom static site for notes",
        "tokens": (1120, 540),
        "messages": 15,
        "body": """**User:** I'm torn between keeping notes in Obsidian with Dataview
queries versus building a small static site generator for them.

**Assistant:** Dataview wins if the notes themselves are the primary
artifact and you want live, queryable views without a build step. A static
site generator wins if you want a polished public-facing output and don't
mind a publish step...

**User:** I think I'll keep Dataview for the working vault and export to
a static site later if I ever want to publish parts of it.
""",
    },
    {
        "offset_days": 0,
        "title": "Reviewing a Python script for a race condition in a manifest file",
        "tokens": (1600, 710),
        "messages": 20,
        "body": """**User:** Two cron jobs might write to the same manifest.jsonl at once —
how do I guard against a race condition there?

**Assistant:** The simplest fix without a database is a file lock
(`fcntl.flock` on POSIX, or a lockfile-based approach that works
cross-platform) held for the read-modify-write cycle, plus documenting
that only one job should ever own that file...

**User:** I'll just document it as single-writer for now and revisit if
I actually add a second writer later.
""",
    },
]

SAMPLE_MEMORY_CANDIDATES = [
    {
        "fact": "User prefers pinned Docker image versions/digests over `latest` — treats reproducibility as a hard requirement for self-hosted stacks.",
        "source": "Sample session: Setting up Docker Compose for a self-hosted stack",
        "days_ago": 6,
    },
    {
        "fact": "User's debugging habit: when a scheduled job silently stops producing output with no errors, first check whether the \"nothing to do\" path is unlogged (looks identical to \"broken\" from the outside).",
        "source": "Sample session: Debugging a cron job that silently stopped firing",
        "days_ago": 4,
    },
]

SAMPLE_PROJECT = """---
type: project
status: active
created: {created}
tags: [project, sample]
sample: true
---

# Self-Hosted Homelab Stack (SAMPLE)

> This is fake demo content generated by `Scripts/seed_sample_data.py` —
> delete it (or the whole file) once you've seen how a populated Projects/
> note looks and are ready to add your own.

## Goal
Consolidate a reverse proxy, a couple of self-hosted apps, and Postgres
onto one Docker Compose stack with pinned versions and healthchecks.

## Repo / location path
~/homelab/docker-compose.yml (example — not a real path)

## Current status
Compose file drafted, networking and volumes worked out. Healthchecks
still need tuning for the Postgres wait condition.

## Durable decisions
- Always pin image versions/digests, never `latest`.
- One bridge network per stack, named volumes for anything stateful.

## Next actions
- [ ] Tune Postgres healthcheck timing
- [ ] Add automated backup for the named volume

## Sources used
- Sample session: Setting up Docker Compose for a self-hosted stack
"""


def _write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


    daily_cand = os.path.join(vault_root, "04-Archives", "Daily")
    daily = daily_cand if os.path.exists(daily_cand) else os.path.join(vault_root, "Daily")

    mr_cand = os.path.join(vault_root, "04-Archives", "Memory-Review")
    memory_review = mr_cand if os.path.exists(mr_cand) else os.path.join(vault_root, "Memory-Review")

    proj_cand = os.path.join(vault_root, "01-Projects")
    projects = proj_cand if os.path.exists(proj_cand) else os.path.join(vault_root, "Projects")

    skills_cand = os.path.join(vault_root, "02-Areas", "Skills")
    skills_notes = skills_cand if os.path.exists(skills_cand) else os.path.join(vault_root, "Skills-Notes")

    now = datetime.now()
    manifest_path = os.path.join(daily, "manifest.jsonl")
    existing_manifest = []
    if os.path.exists(manifest_path):
        with open(manifest_path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    existing_manifest.append(json.loads(line))

    created_files = []

    # --- Daily sessions -----------------------------------------------
    for i, sess in enumerate(SAMPLE_SESSIONS, start=1):
        when = now - timedelta(days=sess["offset_days"])
        y, mo, d = when.strftime("%Y"), when.strftime("%m"), when.strftime("%d")
        session_id = f"sample-session-{i:04d}"
        prompt_tok, completion_tok = sess["tokens"]
        session_md = f"""---
session_id: "{session_id}"
title: "{sess['title']}"
created_at: "{when.strftime('%Y-%m-%d')}T10:00:00+05:30"
message_count: {sess['messages']}
model_config: '{{"_usage_anchor": {{"prompt_tokens": {prompt_tok}, "completion_tokens": {completion_tok}}}}}'
sample: true
---

# {sess['title']}

> Sample/demo session generated by `Scripts/seed_sample_data.py` — not a
> real conversation. Safe to delete.

{sess['body']}
"""
        destpath = os.path.join(daily, y, mo, d, f"{session_id}.md")
        _write(destpath, session_md)
        created_files.append(destpath)
        existing_manifest.append({
            "session_id": session_id,
            "title": sess["title"],
            "path": destpath,
            "format": "md",
            "message_count": sess["messages"],
            "exported_at": when.timestamp(),
        })

    with open(manifest_path, "w", encoding="utf-8") as f:
        for rec in sorted(existing_manifest, key=lambda r: r.get("exported_at") or 0):
            f.write(json.dumps(rec) + "\n")
    created_files.append(manifest_path)

    # --- Token usage log -------------------------------------------------
    token_log = os.path.join(skills_notes, "Token-Usage.log")
    lines = []
    if os.path.exists(token_log):
        with open(token_log, encoding="utf-8") as f:
            lines = f.readlines()
    else:
        lines = ["# Token Usage Log\n"]
    for sess in SAMPLE_SESSIONS:
        when = now - timedelta(days=sess["offset_days"])
        total = sum(sess["tokens"])
        lines.append(f"{when.strftime('%Y-%m-%d')}: {total} tokens (1 session(s)) [sample]\n")
    with open(token_log, "w", encoding="utf-8") as f:
        f.writelines(lines)
    created_files.append(token_log)

    # --- Memory-Review candidates ----------------------------------------
    for i, cand in enumerate(SAMPLE_MEMORY_CANDIDATES, start=1):
        when = now - timedelta(days=cand["days_ago"])
        path = os.path.join(memory_review, f"sample-candidate-{i:02d}.md")
        content = f"""---
sample: true
---

# Memory candidate (SAMPLE) — {when.strftime('%Y-%m-%d')}

> Fake demo candidate generated by `Scripts/seed_sample_data.py`. Safe to
> delete. See [[TEMPLATE]] for the real promotion criteria.

## Candidate
- Fact: {cand['fact']}
- Source/Session: {cand['source']}
- Date observed: {when.strftime('%Y-%m-%d')}

## Verdict
- [ ] Promote to memory
- [ ] Promote to user profile
- [ ] Archive (not durable / not verified)
"""
        _write(path, content)
        created_files.append(path)
        os.utime(path, (when.timestamp(), when.timestamp()))

    # --- Sample project ----------------------------------------------------
    proj_path = os.path.join(projects, "Sample-Homelab-Stack.md")
    _write(proj_path, SAMPLE_PROJECT.format(created=now.strftime("%Y-%m-%d")))
    created_files.append(proj_path)

    print(f"Seeded {len(created_files)} sample files into {vault_root}:")
    for f in created_files:
        print(f"  {os.path.relpath(f, vault_root)}")
    print()
    print("All sample files/entries are tagged `sample: true` in frontmatter")
    print("(or [sample] in the token log). To remove them later:")
    print('  grep -rl "sample: true" Daily/ Memory-Review/ Projects/ | xargs rm')
    print("  (then re-run vault_audit.py / regenerate manifest.jsonl / Token-Usage.log by hand)")


if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else os.environ.get("HERMES_VAULT_PATH")
    if not target:
        print("Usage: seed_sample_data.py <vault_root>  (or set HERMES_VAULT_PATH)")
        sys.exit(1)
    seed(target)
